### ISSUE TITLE
Explain yourself!!!1

### ISSUE THREAD

**Issue by Hacksore** [Rohith-sreedharan/rohith-sreedharan#2]
You purposefully chose to start a shit storm here, why?!?!?

https://github.com/EpicGames/Signup/pull/24

**Comment by Rohith-sreedharan** [comment]
no sir, its just an pr and it wasnt intention

ROHITH 

    On Sunday, 5 June, 2022, 08:06:11 am IST, Sean Boult ***@***.***> wrote:  
 
 


You purposefully chose to start a shit storm here, why?!?!?

EpicGames/Signup#24

**Comment by sammcj** [comment]
Hey @Rohith-sreedharan , I see some people are giving you a hard time.

Please try not to take it personally, people are mean - especially on the internet.

You just made a mistake and it wasn't even a big one, some people got some notifications - so what!

chin up dude! :)

**Comment by Rohith-sreedharan** [comment]
thanks for getting to me, but really it was unknown, thank you

ROHITH 

    On Sunday, 5 June, 2022, 08:29:24 am IST, Sam ***@***.***> wrote:  
 
 


Hey @Rohith-sreedharan , I see some people are giving you a hard time.

Please try not to take it personally, people are mean - especially on the internet.

You just made a mistake and it wasn't even a big one, some people got some notifications - so what!

chin up dude! :)

**Comment by Rohith-sreedharan** [comment]
Thanks for notifying me, and telling me, am sorry

**Comment by Hacksore** [comment]
It does look like it was not intended to be done maliciously but in fact, was unintentional due to a lack of authoritative control on Github and Epic.

Be that as it may, there are some lessons for everyone involved.

- Github should warn you that you are about to send a notification to 300k people or allow controls to prevent it
- Opensource contributors should refrain from partaking in the hacktoberesque style pull requests that give very little value other than them using it to claim to be the maintainer of a well-known project
- People should have never replied to that original PR after the first notification was dispatched as all they did was make it worse

I have no hard feelings for @Rohith-sreedharan at this point as it was just a notification storm.

Never give up on your journey to build great things but consider this valuable lesson to make meaningful contributions to the opensource world 🚀.
