### ISSUE TITLE
Why is he getting so much hate?

### ISSUE THREAD

**Issue by codergautam** [Rohith-sreedharan/rohith-sreedharan#3]
Hey what you did was a very simple mistake and I completely understand.

I don't understand why the pr is getting so much hate and is being blown out of proportion completely.

Tbh it's Unity's fault for even having such a large group, and allowing it to be pinged by anyone.

I'm also from tamil nadu (chennai) and ama nanum tamil pesuven

**Comment by Imshubh69** [comment]
> Hey what you did was a very simple mistake and I completely understand.
> 
> I don't understand why the pr is getting so much hate and is being blown out of proportion completely.
> 
> Tbh it's Unity's fault for even having such a large group, and allowing it to be pinged by anyone.
> 
> I'm also from tamil nadu (chennai) and ama nanum tamil pesuven

Due to this guy thousands of people time got ruined literally ban this guy from everywhere

**Comment by Rohith-sreedharan** [comment]
Am sorryy, but it wasn't my intention to do, thanks

**Comment by GhostSlayer** [comment]
> > Hey what you did was a very simple mistake and I completely understand.
> > I don't understand why the pr is getting so much hate and is being blown out of proportion completely.
> > Tbh it's Unity's fault for even having such a large group, and allowing it to be pinged by anyone.
> > I'm also from tamil nadu (chennai) and ama nanum tamil pesuven
> 
> Due to this guy thousands of people time got ruined literally ban this guy from everywhere

Hmm, 1 minute of 100 years ruined, oh no, how much time got wasted 😔
