### ISSUE TITLE
Dude you are on a video

### ISSUE THREAD

**Issue by Advik-B** [Rohith-sreedharan/rohith-sreedharan#5]
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/NCvnLFF7IYM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
https://www.youtube.com/watch?v=NCvnLFF7IYM

**Comment by Rohith-sreedharan** [comment]
i knew that dude, ya all know whats my fault, its my stupid idea, where i had to add small image but am sorry for the trouble thank you
